FROM zookeeper:latest

# 启动命令示例
# docker run --restart always --name testZk -d -p 2181:2181 -p 3888:3888 -p 8082:8080 zookeeper

# docker客户端连接启动命令示例
# docker run -it --rm --link testZk:zookeeper zookeeper zkCli.sh -server zookeeper